# Generated by Django 5.0.1 on 2024-02-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_bookmark_article_alter_bookmark_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Статья'),
        ),
    ]
