# Generated by Django 5.0.1 on 2024-03-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_messagenotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageNotification',
        ),
    ]
